defaults: &defaults
  app_name: "rocodev-practice"
  domain: "106.186.30.53"
  facebook_app_id: 410688515737314
  facebook_secret: a72b3b7159038211732570f0bcbeda4a
  admin_emails:
    - "wayne@rocodev.com"
  email_sender: "wayne@rocodev.com"
  mailgun:
    api_key: key-4xc66uo1t10ezi738d20fhuanb5m1gk4
    api_host: rocodev-practice.dev

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
